apiVersion: v1
kind: Template
metadata:
  name: git-partition-sync-producer
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: git-partition-sync-producer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: git-partition-sync-producer
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "git-partition-sync-producer design does not adequately account for multiple replicas"
      ignore-check.kube-linter.io/no-readiness-probe: "git-partition-sync-producer does not receive traffic"
    name: git-partition-sync-producer
  spec:
    replicas: ${{REPLICAS}}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: git-partition-sync-producer
    template:
      metadata:
        labels:
          app: git-partition-sync-producer
      spec:
        serviceAccountName: git-partition-sync-producer
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: git-partition-sync-producer
          args: ["-dry-run=${DRY_RUN}"]
          env:
          - name: RECONCILE_SLEEP_TIME
            value: ${RECONCILE_SLEEP_TIME}
          - name: GRAPHQL_QUERY_FILE
            value: ${GRAPHQL_QUERY_FILE}
          - name: WORKDIR
            value: ${WORKDIR}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws.access.key.id
                name: ${VAULT_SECRET_NAME}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws.secret.access.key
                name: ${VAULT_SECRET_NAME}
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                key: aws.region
                name: ${VAULT_SECRET_NAME}
          - name: AWS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                key: aws.s3.bucket
                name: ${VAULT_SECRET_NAME}
          - name: GITLAB_BASE_URL
            valueFrom:
              secretKeyRef:
                key: gitlab.url
                name: ${VAULT_SECRET_NAME}
          - name: GITLAB_USERNAME
            valueFrom:
              secretKeyRef:
                key: gitlab.username
                name: ${VAULT_SECRET_NAME}
          - name: GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                key: gitlab.token
                name: ${VAULT_SECRET_NAME}
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                key: public-key
                name: ${VAULT_SECRET_NAME}
          - name: GRAPHQL_SERVER
            valueFrom:
              secretKeyRef:
                key: endpoint_url
                name: ${GQL_SECRET_NAME}
          - name: GRAPHQL_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: ${GQL_SECRET_NAME}
          - name: GRAPHQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: ${GQL_SECRET_NAME}
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
parameters:
- name: IMAGE
  value: quay.io/app-sre/git-partition-sync-producer
  displayName: git-partition-sync-producer image
  description: git-partition-sync-producer docker image. Defaults to quay.io/app-sre/git-partition-sync-producer
- name: IMAGE_TAG
  value: latest
  displayName: git-partition-sync-producer version
  description: git-partition-sync-producer version which defaults to latest
- name: RECONCILE_SLEEP_TIME
  value: '15m'
- name: DRY_RUN
  description: runs vault-manager in dry-run mode when true
  value: 'true'
- name: GRAPHQL_QUERY_FILE
  value: '/query.graphql'
- name: WORKDIR
  value: '/working'
- name: MEMORY_REQUESTS
  value: 200Mi
- name: MEMORY_LIMIT
  value: 200Mi
- name: CPU_REQUESTS
  value: 100m
- name: CPU_LIMIT
  value: 150m
- name: REPLICAS
  value: '1'
- name: GQL_SECRET_NAME
  value: gql-creds
- name: VAULT_SECRET_NAME
  value: git-partition-sync-producer
